### ISSUE TITLE
切换历史话题后无话题

### ISSUE THREAD

**Issue by Little-3** [BuSheTeam/GoldenEggs#2]
![image](https://user-images.githubusercontent.com/43862603/52027531-bcfac400-2546-11e9-91de-1473c4d140c7.png)
使用这个按钮切换到历史话题后，会提示网络不太顺，同时所有的话题都会消失。之后只能重新进入客户端才能显示出来。

**Comment by Little-3** [comment]
额，好吧，这不只是一个手机的bug，网页本身就有这个bug。debug是400错误

**Comment by BuSheTeam** [comment]
请勿提交此类无用Issue.
